//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAPTRINHWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menus
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int Orders { get; set; }
        public string MenuType { get; set; }
        public string Position { get; set; }
        public Nullable<int> TableId { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public Nullable<int> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
