//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAPTRINHWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Links
    {
        public int Id { get; set; }
        public string Slug { get; set; }
        public string TypeLink { get; set; }
        public int TableId { get; set; }
    }
}
